### ISSUE TITLE
There is an error with the height of the target

### ISSUE THREAD

**Issue by RaydenKonig** [LoneDev6/RPGhuds#1]
If I put an objective with a height of 60, I can go to the same coordinates but at a lower height, as it would be 40, it will detect me as completed.

this is a problem for me because my lobby has several floors

**Comment by LoneDev6** [comment]
The GPS will mark the destination as reached if the player is < 2 blocks of distance from the objective

**Comment by LoneDev6** [comment]
This is not working as intended, I'll fix this in the next update
