### ISSUE TITLE
Balance with words & Colors

### ISSUE THREAD

**Issue by Greazi-Times** [LoneDev6/RPGhuds#12]
The possibility to be able to use colors for the amount and a word like Coins would be great to have.

**Comment by LoneDev6** [comment]
I need more context to understand why and what you need

**Comment by Greazi-Times** [comment]
> I need more context to understand why and what you need

So now you are only able to put in  numbers that will display the balance.
I would like to have a system where you can also add a word for example.
"1.000 coins"

**Comment by LoneDev6** [comment]
Not possible without editing the plugin source code (which is public), you should contact a dev which could integrate that for you.
