### ISSUE TITLE
Add new HUD, error occours.

### ISSUE THREAD

**Issue by Lfeier03** [LoneDev6/RPGhuds#13]
When I edit the source code to add a new HUD, the console issues an error : 

Failed to load PlayerData: Cannot invoke "dev.lone.itemsadder.main.bK.d(int)" because "this.internal" is null 

I don't know how to solve, need your help

**Comment by Lfeier03** [comment]
@LoneDev6

**Comment by LoneDev6** [comment]
> When I edit the source code

I have no idea of what you edited, there is surely something wrong in your code.
Probably the HUD doesn't even exists or the name is wrong.

**Comment by Lfeier03** [comment]
Thank you. Problem solved. The HUD ID is wrong
