### ISSUE TITLE
Enable for all worlds

### ISSUE THREAD

**Issue by PortableGames** [LoneDev6/RPGhuds#17]
Hi, I need some advice. How do I enable rpghuds display in all worlds? My server generates new worlds with random name ( id-536363-6363-6363 etc.) And in the rpghuds config I can't enter them manually.. Can you add something like

worlds:
 - world
 - all-worlds

For use in all worlds on the server?

Or change WHITELISTED worlds to BLACKLISTED?

**Comment by LoneDev6** [comment]
Will be added in the future, thanks

**Comment by PortableGames** [comment]
🍻
