### ISSUE TITLE
RPGHUD COMPASS DOESN'T SHOW WHEN DON'T MOOVE THE VISUAL

### ISSUE THREAD

**Issue by rageyh** [LoneDev6/RPGhuds#18]
Lone una domanda, sto usando l'ultima versione di IA (3.3.0) e vedo che la bussola del compass appena sono fermo si toglie e ricompare quando muovo la visuale. C'è un modo per farla stare fissa e che non scompaia?

Grazie lone sei sempre il migliore

Config:

huds_refresh_interval_ticks: 15
huds_high_frequency_refresh_interval_ticks: 1
money:
  enabled: false
  offset: 91
  papi_placeholder: '%vault_eco_balance_formatted%'
  worlds:
  - world
  - world_nether
  - world_the_end
compass:
  enabled: true
  offset: -8
  worlds:
  - world
  - night
quiver:
  enabled: false
  offset:
    normal: -96
    when_offhand_shown: -124
  content_update_ticks: 100
  worlds:
  - world
  - night
arrow_target:
  enabled: false
  offset: -98
  worlds:
  - world
  - night
lang:
  hud_not_found: '&6Hud not found!'
  wrong_usage: '&cWrong command usage.'
  destination_set: '&aDestination set.'
  destination_removed: '&7Destination removed.'
log:
  debug: false

**Comment by icansc187** [comment]
same issue :(

**Comment by LoneDev6** [comment]
C'è un plugin che interferisce molto, probabilmente uno che invia un messaggio nella actionbar.
Rimuovili tutti e controlla.
