### ISSUE TITLE
There's an error when load "money" hud

### ISSUE THREAD

**Issue by Sam-Chai** [LoneDev6/RPGhuds#20]
```
[RPGhuds]: Failed to load PlayerData: Cannot invoke "net.milkbowl.vault.economy.Economy.getBalance(org.bukkit.OfflinePlayer)" because "dev.lone.rpghuds.Main.econ" is null
```
And the player can't see any huds, but when I turn money hud off, then gets normally.

**Comment by LoneDev6** [comment]
Install Vault.
Also install EssentialsX  or another economy plugin.

Everything is noted in the plugin page clearly.
