### ISSUE TITLE
RPG Hud cannot compatible with CMI

### ISSUE THREAD

**Issue by Sam-Chai** [LoneDev6/RPGhuds#21]
```
              Install Vault.
Also install EssentialsX  or another economy plugin.

Everything is noted in the plugin page clearly.

_Originally posted by @LoneDev6 in https://github.com/LoneDev6/RPGhuds/issues/20#issuecomment-1397172421_
```

But I don't know the CMI is a exact economic plugin, but after I turn on the "economy" functions in CMI's config, the CMI & vault runs normally, and I also can use "/cmi money" to execute my money.
If the CMI is the currently eco plugin, then why does RPGHud crash?

**Comment by Sam-Chai** [comment]
#20

**Comment by LoneDev6** [comment]
Please read plugins guides.
https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

Ask CMI author about that, I'm not its developer.

![image](https://user-images.githubusercontent.com/27242001/213656510-028ad2bc-b513-4655-af92-83f609308e1b.png)
