### ISSUE TITLE
Issue with HUD

### ISSUE THREAD

**Issue by CertifiedCallatic** [LoneDev6/RPGhuds#23]
Hi,

I am using latest version IA and latest version RPGHuds and having this issue, would hope to fix this issue with the compass been missing and the front of the cash having a wierd icon, unable to fix any of this.

![9149c74fd54b0a790b9ab013c2726eb1](https://user-images.githubusercontent.com/71158669/215302064-ea0219a1-81e3-47d9-ac54-9571c560aaaf.png)

**Comment by Sonicscream** [comment]
@CertifiedCallatic I had the same issue yesterday. I changed the placeholder variable in the RPG huds plugin folder config file with one that included only the numerical amount of my currency and no letters or color codes. I think I used %vault_eco_balance_fixed% or something similar.

About the compass: I can't get mine to work either.

**Comment by CertifiedCallatic** [comment]
Thank you, that got rid of the little symbol, would be good though if we could use formatted without any issues :P

**Comment by LoneDev6** [comment]
> would hope to fix this issue with the compass been missing

Properly add some more information about this.
Did you use the compass command to get the compass HUD added?
It's not visible 24/7.

> and the front of the cash having a wierd icon

It's because you're using the wrong PAPI placeholder. Use one which doesn't include the currency symbol as explained in the RPGhuds installation tutorial.

**Comment by CertifiedCallatic** [comment]
Command does not work at all to bring compass on, enabled for it to be always on and still does not show so don't know how you have marked this as invalid when its totally valid bug.

**Comment by LoneDev6** [comment]
Make sure your world is enabled in config.yml of rpghuds
