### ISSUE TITLE
Money hud outline

### ISSUE THREAD

**Issue by SakuraGoose** [LoneDev6/RPGhuds#24]
The black outline of the money is a bit irritating is there a way to remove it

![image](https://user-images.githubusercontent.com/86365891/216999881-b370570f-5155-4302-92da-05c14540afe2.png)

**Comment by SNokerYT** [comment]
+1

**Comment by LoneDev6** [comment]
Seems new versions of the game added shadow to actionbar texts, this wasn't the case in previous game versions.
I will have to edit all the characters and remove the outline and still provide the old icons for older versions maybe.

I first have to check which Minecraft version introduced actionbar text shadows.

**Comment by LoneDev6** [comment]
I did various tests and seems 1.19+ have this issue.
In the next update you will have to delete the folder `ItemsAdder/contents/rpghuds/textures/`, then open `config.yml` of RPGhuds and set `legacy_1_18_and_lower_textures: true`, then run `/iazip`.

## 1.17.1
![image](https://user-images.githubusercontent.com/27242001/229177154-ae166aae-4d4b-45e2-ad9d-17ce1b8adb8e.png)

-----

## 1.18.2

![image](https://user-images.githubusercontent.com/27242001/229177450-0c9d9487-e777-4e01-85d6-0589b191cceb.png)

-----

## 1.19.4

![image](https://user-images.githubusercontent.com/27242001/229177339-7583ff7d-01d8-4707-b905-e809c6706c1a.png)
