### ISSUE TITLE
RPG Compass

### ISSUE THREAD

**Issue by CertifiedCallatic** [LoneDev6/RPGhuds#25]
Hi,

When I try use the /rpgcompass, it just tells me wrong usage command for anything try and can not get the compass icon showing

**Comment by LoneDev6** [comment]
The compass command has an autocomplete, press tab while writing.
The command asks you to put world name and coordinates to decide where to make the compass look at.

Be more precise about which specific command arguments are not working and causing error.
Post also the error (as text please, not screenshot).
