### ISSUE TITLE
Outdated Source Code on Github compared to Spigot

### ISSUE THREAD

**Issue by Aitooor** [LoneDev6/RPGhuds#26]
I need to edit the source code from RPGHuds, but it is outdated from the latest version of spigot(that use the latest DataPack structure for ItemsAdder). I would really appreciate it if you could upload the new code. To be able to add new things or modify others to my need.

Thanks 😄

**Comment by ErikViceCode** [comment]
decompile

**Comment by LoneDev6** [comment]
Done

**Comment by Aitooor** [comment]
> Done

Thanks for upgrade the project ❤️ 

Could you update pom.xml please? Main plugin version from 1.0.1 to 1.2.0 and PlaceholderAPI to the latest version "2.11.2" from "2.10.10"? I could do a PR if you prefer

**Comment by LoneDev6** [comment]
I'll do it as soon as I find the time

**Comment by Aitooor** [comment]
> I'll do it as soon as I find the time

No problem. Thanks a lot
