### ISSUE TITLE
Squares instead of images

### ISSUE THREAD

**Issue by marcjoancr** [LoneDev6/RPGhuds#27]
I've disabled every hud because squares where showing instead of images and after unzip still shows up those squares as you can see in the image:

![2023-03-17_21 25 18](https://user-images.githubusercontent.com/14807142/226030546-bff36e9c-2f87-43d5-a69e-20ac0caca33b.png)

Version 1.19.3, running on Spigot

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by marcjoancr** [comment]
Just have those logs
```
Missing sound for event: minecraft:item.goat_horn.play
Missing sound for event: minecraft:entity.goat.screaming.horn_break
```
I'll check what's happening, do not worry ;) thanks for the link, it realy helped me
