### ISSUE TITLE
RPGHuds Hide Not working

### ISSUE THREAD

**Issue by zikehalil3535** [LoneDev6/RPGhuds#28]
![image](https://user-images.githubusercontent.com/88826436/226142647-f883d4dd-a293-4019-8eb6-848f1525c601.png)
![image](https://user-images.githubusercontent.com/88826436/226142658-17253292-03ce-4a0b-b910-7cc9e42d3721.png)

**Comment by zikehalil3535** [comment]
Any updates?

**Comment by LoneDev6** [comment]
I investigated and this is a bug of RPGhuds but also of ItemsAdder.
This will be fixed in the upcoming updates for both plugins.
