### ISSUE TITLE
[Bug? Question?] hud does not display, loading time error

### ISSUE THREAD

**Issue by Yurinann** [LoneDev6/RPGhuds#3]
Error when load / /iazip:

```
[RPGhuds] Failed to load PlayerData: Cannot invoke "net.milkbowl.vault.economy.Economy.getBalance(org.bukkit.OfflinePlayer)" because "dev.lone.rpghuds.Main.econ" is null
```

I installed the requested prefix and did not change any default settings, hud does not show up, using "/rpghuds show ..." When I use "/rpghuds show ...", it shows "Hud not found!"

Paper 1.18.1, Azul zulu 17

**Comment by LoneDev6** [comment]
It works fine on my server.
Installed:
- Vault
- EssentialsX
- PlaceholderAPI
- [Papi Vault placeholders](https://api.extendedclip.com/expansions/vault/)


It's hard to help you without any full server log.

**Comment by Yurinann** [comment]
> It works fine on my server. Installed:
> 
> * Vault
> * EssentialsX
> * PlaceholderAPI
> * [Papi Vault placeholders](https://api.extendedclip.com/expansions/vault/)
> 
> It's hard to help you without any full server log.

Sorry for my oversight, is it possible to use the variables of other economy plugins here?

Thank you for your reply.

**Comment by LoneDev6** [comment]
yes, change it in config.yml of RPGhuds
