### ISSUE TITLE
"net.milkbowl.vault.economy.Economy.getBalance(org.bukkit.OfflinePlayer)" because "dev.lone.rpghuds.Main.econ" is null

### ISSUE THREAD

**Issue by Blskk** [LoneDev6/RPGhuds#32]
UPDATE to ItemsAdder 3.4.1-r5 or greater.
install all the dependecies (list below)
run /papi ecloud download Vault
run /papi reload
stop the server
install this plugin (paste the JAR inside the plugins folder)
start server
open plugins\RPGhuds\config.yml file and add your worlds names
use the command /iazip

/rpghuds show rpghuds:arrow_target
It says：Hud not found!

paper1.19.2

**Comment by LoneDev6** [comment]
Update ItemsAdder and restart the server.
Post the whole server log.

**Comment by D4W3-GS** [comment]
Hi, im having the same problem. :D Here is my server log:
https://pastebin.com/urnbe4X1

**Comment by Blskk** [comment]
> 

https://mclo.gs/uztQE9s

**Comment by LoneDev6** [comment]
> [11:36:35] [Server thread/ERROR]: [RPGhuds] Failed to load PlayerData: Cannot invoke "net.milkbowl.vault.economy.Economy.getBalance(org.bukkit.OfflinePlayer)" because "dev.lone.rpghuds.Main.econ" is null

Install an economy plugin, for example EssentialsX.


It was clearly noted in the plugin page.
![image](https://github.com/LoneDev6/RPGhuds/assets/27242001/58e1b286-b74c-4041-9017-00f82de6d68f)
