### ISSUE TITLE
未完成的对话

### ISSUE THREAD

**Issue by Blskk** [LoneDev6/RPGhuds#33]
根据[#32](https://github.com/LoneDev6/RPGhuds/issues/32)
Install an economy plugin, for example EssentialsX.
我安装了cmi，难道ia不支持它吗

**Comment by LoneDev6** [comment]
It's a CMI issue.
You have to install CMI vault patched.
It's not my fault if CMI requires another Vault version.

https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

Download: https://www.zrips.net/wp-content/uploads/2020/07/Vault-1.7.3.jar

![image](https://github.com/LoneDev6/RPGhuds/assets/27242001/ca56b349-cf99-4448-b968-274aa0773aa0)
