### ISSUE TITLE
RPGhuds - IA with Optifine

### ISSUE THREAD

**Issue by MrHarebug** [LoneDev6/RPGhuds#34]
Hello.

I need help with RPGhuds and Optifine players.

I implement to RPGhuds my own Placeholder reader for Economy (bcs I use own economy system)

Everything works but when I want add blank spaces - Replace "*" char with 2px of picture with transparent background it wont show for players with Optifines. Also I try add pixels behind and after number but still OF replace blank.
First I think problem is with my placeholder but I try placeholder from CMI - Playtime and there is result:

![obrázok](https://github.com/LoneDev6/RPGhuds/assets/69869677/eba88080-c7cd-4549-9ab8-23b0037e4c8a)

Thanks for help ^^

**Comment by LoneDev6** [comment]
Set the blank background to alpha 5/255 or 8/255.
Minecraft removes completely transparent pixels otherwise.
It's how the game works.

**Comment by MrHarebug** [comment]
Sorry for reopen but Minecraft is screen on top where it works... problem is with optifine players
