### ISSUE TITLE
 [RPGhuds] §cFailed to load PlayerData: Cannot invoke "net.milkbowl.vault.economy.Economy.getBalance(org.bukkit.OfflinePlayer)" because "dev.lone.rpghuds.Main.econ" is null

### ISSUE THREAD

**Issue by N1D4L0S** [LoneDev6/RPGhuds#39]
[RPGhuds] §cFailed to load PlayerData: Cannot invoke "net.milkbowl.vault.economy.Economy.getBalance(org.bukkit.OfflinePlayer)" because "dev.lone.rpghuds.Main.econ" is null

**Comment by LoneDev6** [comment]
install vault

**Comment by N1D4L0S** [comment]
Im using cmi.. I have vault

**Comment by N1D4L0S** [comment]
[RPGhuds] §cFailed to load PlayerData: Cannot invoke "ia.m.bj.a(String)" because the return value of "dev.lone.itemsadder.api.FontImages.PlayerHudsHolderWrapper.getInternal()" is null

**Comment by LoneDev6** [comment]
Read the guide of CMI and install its custom Vault fix: https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

![image](https://github.com/LoneDev6/RPGhuds/assets/27242001/b37c6a09-f4b8-46eb-8b42-3eb8e54ecd2e)


-----

> [RPGhuds] §cFailed to load PlayerData: Cannot invoke "ia.m.bj.a(String)" because the return value of "dev.lone.itemsadder.api.FontImages.PlayerHudsHolderWrapper.getInternal()" is null

it's impossible to help you without the full server log

**Comment by N1D4L0S** [comment]
Already done, ive installed the injector too

**Comment by N1D4L0S** [comment]
I dont get the econ error anymore.
But the previous one.

**Comment by LoneDev6** [comment]
it's impossible to help you without the full server log

**Comment by N1D4L0S** [comment]
Yep ill provide it asap 🫡

**Comment by svaningelgem** [comment]
I had the same issue. The reason is that Vault was loaded AFTER ItemsAdder. So it couldn't find the provider.
Reloading the rpg plugin made these pesky entries go away. But there should be some additional verification I guess?
