### ISSUE TITLE
Reporting Bugs

### ISSUE THREAD

**Issue by DarrienNN** [LoneDev6/RPGhuds#4]
Hello I want to report IA(Addon) [ADDON] RPGHuds not working/spam error

Error:
https://pastebin.com/ie9tueR8

**Comment by DarrienNN** [comment]
Server version: 1.18.1
Server Type: Pufferfish (Tried using PaperMc, Purpur jar but still same got the error)
ItemAdders version: 2.5.4-beta2

**Comment by LoneDev6** [comment]
I need the full log, this is only a part of it

**Comment by DarrienNN** [comment]
The problem from **GamePoints** plugin. The Author say will fix it
