### ISSUE TITLE
compas

### ISSUE THREAD

**Issue by MINIMANGITGUB** [LoneDev6/RPGhuds#41]
when I change the compass position from -14 to -1 everything is fine, but when from 0 and above, everything breaks and a square symbol appears
[images.zip](https://github.com/LoneDev6/RPGhuds/files/12838905/images.zip)
![image](https://github.com/LoneDev6/RPGhuds/assets/92558688/3733649c-e8cf-4e4b-a9f6-f25d7b831840)

**Comment by MINIMANGITGUB** [comment]
ver. 1.20.1 purpur

**Comment by MINIMANGITGUB** [comment]
maybe you can add a placeholder? otherwise it doesn't work with the happyhud plugin(

**Comment by LoneDev6** [comment]
Happy hud and RPGhuds are not compatible and can never will be for various game limitations

**Comment by MINIMANGITGUB** [comment]
Without the Happy Hood plugin I also can’t move it up

**Comment by MINIMANGITGUB** [comment]
up to height 16 everything is fine, then an error
y_position must be lower or equal to scale_ratio (or png height)

**Comment by LoneDev6** [comment]
edit each compass PNG file and add some transparent space on the bottom.
This is not a limitation of itemsadder, it's a limitation of the game.

**Comment by MINIMANGITGUB** [comment]
thanks! You plugins top!

**Comment by LoneDev6** [comment]
> thanks! You plugins top!

Thanks a lot!
