### ISSUE TITLE
Since the latest update the compass hasn't been in the correct place

### ISSUE THREAD

**Issue by FinlayHDev** [LoneDev6/RPGhuds#5]
Compass is now in the wrong place since the update

![image](https://user-images.githubusercontent.com/73852683/152677861-02fb9fb0-163a-4ef1-b0bc-9eb2f031ad50.png)

**Comment by LoneDev6** [comment]
It works fine for me.
You might need to delete the rpghuds folder from the itemsadder `data/items_packs` and `data/resource_pack/assets/` folders, then start the server and run `/iazip`

**Comment by FinlayHDev** [comment]
> It works fine for me. You might need to delete the rpghuds folder from the itemsadder `data/items_packs` and `data/resource_pack/assets/` folders, then start the server and run `/iazip`

Just done this, still happening.

**Comment by LoneDev6** [comment]
I can't reproduce the issue

**Comment by FinlayHDev** [comment]
Is there a way to regen the file for it?

**Comment by LoneDev6** [comment]
You need to delete the rpghuds folder from the itemsadder `data/items_packs` and `data/resource_pack/assets/` folders, then start the server and run `/iazip`.
Also try to delete the RPGhuds plugin folder itself.

**Comment by Katalijst** [comment]
@LoneDev6 I have the same problem, I edited nothing from the RPGhuds files 
![image](https://user-images.githubusercontent.com/49079167/159919150-5eae97f7-8a75-4975-8bff-20e610a43f13.png)

**Comment by Katalijst** [comment]
I had to change the offset from 6 to -8 in the config file to make it work

**Comment by LoneDev6** [comment]
Thanks for the help!
