### ISSUE TITLE
Bug with actionbars?

### ISSUE THREAD

**Issue by LcyDev** [LoneDev6/RPGhuds#6]
![image](https://user-images.githubusercontent.com/72966048/152917121-d94e03bf-0f13-4a85-8f29-56ded3b99bf4.png)

![image](https://user-images.githubusercontent.com/72966048/152917129-fdf4c8ea-e599-4e26-b19e-4de6463aa489.png)

They overlapse constantly with a plugin called Towny.
It also happens with /title actionbar "something"

**Comment by LoneDev6** [comment]
This can't be fixed, it's a limitation of the game.
You can show HUDs or the actionbar, not both at the same time.
