### ISSUE TITLE
[bug] when I dive under the water, the air bubbles cover the money.

### ISSUE THREAD

**Issue by MrJorman** [LoneDev6/RPGhuds#7]
when I dive under the water, the air bubbles cover the money.Please make sure that money could disappear if air bubbles appear under water, and as they recover and disappear, money appears, so it is done on Realm Origins.

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/156425393-8eb7e4f7-a731-4586-a716-8089a56127eb.png)

**Comment by MrJorman** [comment]
and if it's not difficult, make sure that the money is separated by commas, as on Realm Origins, example: 1,005 with a capacity of 1k

**Comment by MrJorman** [comment]
or make this HUD move up automatically, and then go down.

**Comment by MrJorman** [comment]
and?

**Comment by MrJorman** [comment]
fixed no?

**Comment by nhanledev** [comment]
edit your hud config file
```
    show:
      auto: false
      creative: false
      underwater: false
      riding: true
```

**Comment by MrJorman** [comment]
And how to make the money not disappear, but move up the line?

**Comment by MrJorman** [comment]
When I'm underwater

**Comment by LoneDev6** [comment]
There is no way because of a limitation of the game.
Would require me to create two different huds, one for underwater and one for ouside of water, it's a waste of resources.

Also stop commenting on old Github reports, this was closed on January.
